//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKutuphane.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBL_YAZAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_YAZAR()
        {
            this.TBL_KITAP = new HashSet<TBL_KITAP>();
        }
    
        public int ID { get; set; }

        [Required(ErrorMessage ="Yazar Adýný Boþ Geçemezsiniz!")]
        public string Ad { get; set; }

        [StringLength(20, ErrorMessage ="20 Karakteri Geçemezsiniz!")]
        public string Soyad { get; set; }
        public string Detay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_KITAP> TBL_KITAP { get; set; }
    }
}
