//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCv.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CVDBEntities : DbContext
    {
        public CVDBEntities()
            : base("name=CVDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_ABOUT> TBL_ABOUT { get; set; }
        public virtual DbSet<TBL_ADMIN> TBL_ADMIN { get; set; }
        public virtual DbSet<TBL_AWARDS> TBL_AWARDS { get; set; }
        public virtual DbSet<TBL_CONTACT> TBL_CONTACT { get; set; }
        public virtual DbSet<TBL_EDUCATION> TBL_EDUCATION { get; set; }
        public virtual DbSet<TBL_EXPERIENCE> TBL_EXPERIENCE { get; set; }
        public virtual DbSet<TBL_INTERESTS> TBL_INTERESTS { get; set; }
        public virtual DbSet<TBL_SKILLS> TBL_SKILLS { get; set; }
    }
}
